"""
一次性写入通用医学文献词汇表
"""
import csv
import os

VOCAB_FILE = r"C:\Users\年年\medical-translator\vocabulary.csv"

VOCAB = """
英文术语,中文译名,学科
ablation,消融术,手术
abscess,脓肿,病理
absorption,吸收,生理
acidosis,酸中毒,病理生理
acinus,腺泡,组织学
action potential,动作电位,生理
acute,急性的,临床
adenoma,腺瘤,病理
adhesion,粘连,病理
adjuvant,辅助的,肿瘤
adrenal,肾上腺的,解剖
adverse effect,不良反应,药理
aetiology,病因学,基础医学
afferent,传入的,生理
agglutination,凝集反应,免疫
agonist,激动剂,药理
alkalosis,碱中毒,病理生理
allograft,同种异体移植物,移植
alveolus,肺泡,组织学
amino acid,氨基酸,生化
amyloid,淀粉样蛋白,病理
anaerobic,厌氧的,微生物
anaesthesia,麻醉,麻醉
analgesia,镇痛,疼痛
anaphylaxis,过敏反应,免疫
anastomosis,吻合术,手术
aneurysm,动脉瘤,病理
angiogenesis,血管生成,生理
anomaly,异常,病理
antagonist,拮抗剂,药理
antibody,抗体,免疫
antigen,抗原,免疫
antioxidant,抗氧化剂,生化
aorta,主动脉,解剖
aphasia,失语症,神经
apoptosis,细胞凋亡,细胞生物学
arrhythmia,心律失常,心血管
arthroplasty,关节成形术,骨科
ascites,腹水,消化
ataxia,共济失调,神经
atherosclerosis,动脉粥样硬化,病理
atrophy,萎缩,病理
autoimmune,自身免疫的,免疫
autophagy,自噬,细胞生物学
bacteremia,菌血症,感染
benign,良性的,肿瘤
bioavailability,生物利用度,药理
biomarker,生物标志物,检验
biopsy,活检,病理
biosynthesis,生物合成,生化
blastocyst,囊胚,生殖
bolus,团注,临床
bronchospasm,支气管痉挛,呼吸
cachexia,恶病质,肿瘤
calcification,钙化,病理
carcinogen,致癌物,肿瘤
carcinoma,癌,肿瘤
cardiomyopathy,心肌病,心血管
cartilage,软骨,组织学
cascade,级联反应,生化
catheter,导管,护理
causalgia,灼痛,神经
cellular,细胞的,细胞生物学
chemotaxis,趋化性,免疫
chromosome,染色体,遗传
chronic,慢性的,临床
cilia,纤毛,组织学
circadian,昼夜节律的,生理
cirrhosis,肝硬化,消化
clone,克隆,分子生物学
coagulation,凝固,血液
cognitive,认知的,神经
collagen,胶原蛋白,生化
comorbidity,共病,临床
compliance,依从性,临床
conduction,传导,生理
congenital,先天性的,儿科
contraindication,禁忌症,临床
convalescence,恢复期,临床
coronary,冠状动脉的,解剖
cortex,皮质,解剖
cryotherapy,冷冻疗法,治疗
cytokine,细胞因子,免疫
cytology,细胞学,病理
cytotoxicity,细胞毒性,免疫
debridement,清创术,外科
decompensation,失代偿,病理生理
degeneration,变性,病理
dementia,痴呆,神经
demyelination,脱髓鞘,神经
dendritic,树突状的,组织学
denervation,去神经,神经
deoxyribonucleic acid,脱氧核糖核酸,分子生物学
depolarization,去极化,生理
dermatitis,皮炎,皮肤
detoxification,解毒,生化
diagnosis,诊断,临床
dialysis,透析,肾病
diaphoresis,发汗,症状
diastole,舒张期,心血管
differentiation,分化,细胞生物学
diffusion,弥散,生理
dilatation,扩张,病理
disease,疾病,临床
disorder,障碍,临床
dissection,剥离,病理
disseminated,播散性的,病理
distal,远端的,解剖
diuresis,利尿,生理
diverticulum,憩室,消化
dosage,剂量,药理
duct,导管,解剖
dysfunction,功能障碍,病理生理
dysplasia,异型增生,病理
dyspnea,呼吸困难,症状
dystrophy,营养不良,病理
edema,水肿,症状
efferent,传出的,生理
effusion,渗出液,病理
electrolyte,电解质,生化
embolism,栓塞,病理
embryo,胚胎,生殖
emission,发射,影像
endemic,地方性的,公卫
endocytosis,胞吞作用,细胞生物学
endogenous,内源性的,生理
endoscopy,内镜检查,临床
endothelium,内皮,组织学
enteric,肠的,解剖
enzyme,酶,生化
eosinophil,嗜酸性粒细胞,血液
epidemiology,流行病学,公卫
epigenetics,表观遗传学,遗传
epithelium,上皮,组织学
erosion,糜烂,病理
erythema,红斑,皮肤
erythrocyte,红细胞,血液
etiology,病因学,临床
exacerbation,加重,临床
excision,切除术,外科
excretion,排泄,生理
exogenous,外源性的,生理
exon,外显子,遗传
expression,表达,分子生物学
extracellular,细胞外的,细胞生物学
extravasation,外渗,病理
exudate,渗出物,病理
fascia,筋膜,解剖
fasting,禁食的,临床
fatigue,疲劳,症状
ferritin,铁蛋白,检验
fetus,胎儿,妇产科
fibrillation,纤维性颤动,心血管
fibrin,纤维蛋白,血液
fibrinolysis,纤维蛋白溶解,血液
fibroblast,成纤维细胞,组织学
fibrosis,纤维化,病理
fistula,瘘管,病理
flora,菌群,微生物
fluorescence,荧光,检验
follicle,滤泡,组织学
fracture,骨折,骨科
ganglion,神经节,解剖
gangrene,坏疽,病理
gastrin,胃泌素,消化
gastrointestinal,胃肠道的,消化
gene,基因,遗传
genome,基因组,遗传
genotype,基因型,遗传
gestation,妊娠,妇产科
gland,腺体,解剖
glomerulus,肾小球,组织学
glucagon,胰高血糖素,内分泌
glucocorticoid,糖皮质激素,内分泌
gluconeogenesis,糖异生,生化
glycogen,糖原,生化
glycolysis,糖酵解,生化
glycosylation,糖基化,生化
gonad,性腺,解剖
gravid,妊娠的,妇产科
haematemesis,呕血,消化
haematology,血液学,血液
haematoma,血肿,病理
haematuria,血尿,泌尿
haemoglobin,血红蛋白,血液
haemolysis,溶血,血液
haemorrhage,出血,病理
haemostasis,止血,血液
healing,愈合,临床
hemodynamics,血流动力学,生理
hepatic,肝的,解剖
hepatocyte,肝细胞,组织学
hereditary,遗传性的,遗传
hernia,疝,外科
heterogeneity,异质性,病理
histamine,组胺,免疫
histology,组织学,基础医学
homeostasis,内稳态,生理
hormone,激素,内分泌
hydrolysis,水解,生化
hyperglycemia,高血糖,内分泌
hyperplasia,增生,病理
hypersensitivity,超敏反应,免疫
hypertension,高血压,心血管
hypertrophy,肥大,病理
hypoglycemia,低血糖,内分泌
hypoplasia,发育不全,病理
hypotension,低血压,心血管
hypothalamus,下丘脑,神经
hypotonia,肌张力减低,神经
hypoxia,缺氧,病理生理
iatrogenic,医源性的,临床
idiopathic,特发性的,临床
ileum,回肠,解剖
immune response,免疫应答,免疫
immunocompromised,免疫功能受损的,免疫
immunodeficiency,免疫缺陷,免疫
immunoglobulin,免疫球蛋白,免疫
immunosuppression,免疫抑制,免疫
implant,植入物,外科
incidence,发病率,公卫
incision,切口,外科
incontinence,失禁,泌尿
infarction,梗死,病理
infection,感染,感染
infestation,侵染,感染
inflammation,炎症,病理
ingestion,摄入,临床
inhalation,吸入,临床
inheritance,遗传,遗传
inhibitor,抑制剂,药理
innate,先天的,免疫
innervation,神经支配,神经
inoculation,接种,微生物
insulin,胰岛素,内分泌
integrin,整合素,细胞生物学
interferon,干扰素,免疫
interleukin,白细胞介素,免疫
interstitial,间质的,组织学
intracellular,细胞内的,细胞生物学
intravenous,静脉内的,临床
intrinsic,内源性的,生理
intron,内含子,遗传
invasiveness,侵袭性,肿瘤
ischemia,缺血,病理
jaundice,黄疸,症状
juxtaglomerular,近球旁的,组织学
karyotype,核型,遗传
keratin,角蛋白,生化
kinase,激酶,生化
laceration,撕裂伤,外科
lactation,泌乳,妇产科
laparotomy,剖腹术,外科
larynx,喉,解剖
latency,潜伏期,感染
lesion,病变,病理
leukocyte,白细胞,血液
leukotriene,白三烯,免疫
ligament,韧带,解剖
ligation,结扎,外科
lipoprotein,脂蛋白,生化
lumen,管腔,解剖
lymphocyte,淋巴细胞,血液
lysis,溶解,生化
lysosome,溶酶体,细胞生物学
macrophage,巨噬细胞,血液
malabsorption,吸收不良,消化
malformation,畸形,病理
malignancy,恶性肿瘤,肿瘤
mammography,乳腺X线摄影,影像
manometry,测压法,消化
marrow,骨髓,血液
mast cell,肥大细胞,血液
maternal,母体的,妇产科
mediastinum,纵隔,解剖
medulla,髓质,解剖
meiosis,减数分裂,遗传
membrane,膜,细胞生物学
meninges,脑膜,解剖
menstruation,月经,妇产科
mesenchyme,间充质,组织学
metabolite,代谢物,生化
metaplasia,化生,病理
metastasis,转移,肿瘤
microbiology,微生物学,微生物
microcirculation,微循环,生理
microglia,小胶质细胞,神经
microorganism,微生物,微生物
microscope,显微镜,设备
mitochondrion,线粒体,细胞生物学
mitosis,有丝分裂,细胞生物学
morbidity,发病率,公卫
morphology,形态学,基础医学
mortality,死亡率,公卫
motility,运动功能,生理
mucosa,黏膜,组织学
muscle,肌肉,解剖
mutagen,诱变剂,遗传
mutation,突变,遗传
myelin,髓鞘,神经
myocardium,心肌,解剖
myocyte,肌细胞,组织学
myopathy,肌病,神经
naevus,痣,皮肤
natriuretic,利尿钠的,心血管
nausea,恶心,症状
necrosis,坏死,病理
neonatal,新生儿的,儿科
neoplasm,新生物,肿瘤
nephron,肾单位,解剖
nerve,神经,解剖
neuralgia,神经痛,神经
neuritis,神经炎,神经
neurogenesis,神经发生,神经
neuron,神经元,神经
neuropathy,神经病,神经
neurotransmitter,神经递质,神经
neutropenia,中性粒细胞减少,血液
neutrophil,中性粒细胞,血液
nociceptor,伤害感受器,神经
node,淋巴结,解剖
nodule,结节,病理
nucleolus,核仁,细胞生物学
nucleus,细胞核,细胞生物学
nutrient,营养素,营养
obesity,肥胖,公卫
obstruction,梗阻,病理
occlusion,闭塞,病理
ocular,眼的,眼科
oedema,水肿,病理
olfactory,嗅觉的,神经
oocyte,卵母细胞,生殖
operation,手术,外科
organelle,细胞器,细胞生物学
organism,生物体,微生物
osmosis,渗透,生理
ossification,骨化,骨科
osteoblast,成骨细胞,骨科
osteoclast,破骨细胞,骨科
osteoporosis,骨质疏松,骨科
ovarian,卵巢的,妇产科
ovulation,排卵,生殖
oxidation,氧化,生化
oxygenation,氧合,生理
pacemaker,起搏器,心血管
pancreas,胰腺,消化
paralysis,瘫痪,神经
parasite,寄生虫,感染
parenchyma,实质,组织学
paresis,轻瘫,神经
pathogen,病原体,感染
pathogenesis,发病机制,基础医学
pathology,病理学,基础医学
pathophysiology,病理生理学,基础医学
pathway,通路,生化
peptide,肽,生化
perforation,穿孔,病理
perfusion,灌注,生理
perioperative,围手术期的,麻醉
peristalsis,蠕动,生理
peritoneum,腹膜,解剖
permeability,通透性,生理
phagocytosis,吞噬作用,免疫
pharmacodynamics,药效动力学,药理
pharmacokinetics,药代动力学,药理
pharynx,咽,解剖
phenotype,表型,遗传
phosphorylation,磷酸化,生化
physiology,生理学,基础医学
pinocytosis,吞饮作用,细胞生物学
placenta,胎盘,妇产科
plaque,斑块,病理
plasma,血浆,血液
plasmid,质粒,分子生物学
platelet,血小板,血液
pleura,胸膜,解剖
pneumonia,肺炎,呼吸
pneumothorax,气胸,呼吸
polymorphism,多态性,遗传
polypeptide,多肽,生化
polyposis,息肉病,消化
postoperative,术后,外科
potassium,钾,生化
precursor,前体,生化
pregnancy,妊娠,妇产科
prenatal,产前的,妇产科
prevalence,患病率,公卫
prognosis,预后,临床
proliferation,增殖,细胞生物学
prophylaxis,预防,临床
proprioception,本体感觉,神经
prostaglandin,前列腺素,生化
prostate,前列腺,泌尿
protease,蛋白酶,生化
proteasome,蛋白酶体,生化
proteinuria,蛋白尿,肾病
protocol,方案,临床研究
proximal,近端的,解剖
pruritus,瘙痒,症状
psychosis,精神病,精神
pulmonary,肺的,呼吸
pulse,脉搏,生理
puncture,穿刺,临床
purpura,紫癜,血液
pus,脓液,病理
pyrexia,发热,症状
radiotherapy,放射治疗,肿瘤
receptor,受体,药理
recombination,重组,遗传
recurrence,复发,临床
reflex,反射,生理
regeneration,再生,细胞生物学
regimen,方案,药理
regurgitation,反流,消化
rejection,排斥,移植
remission,缓解,肿瘤
renal,肾的,肾病
repair,修复,外科
reperfusion,再灌注,心血管
replication,复制,分子生物学
resection,切除,外科
resistance,耐药性,药理
resorption,吸收,生理
respiration,呼吸,生理
resuscitation,复苏,急诊
retardation,发育迟缓,儿科
reticulocyte,网织红细胞,血液
retina,视网膜,眼科
retinoblastoma,视网膜母细胞瘤,肿瘤
reuptake,再摄取,神经
revascularization,血运重建,心血管
rheumatoid,类风湿的,风湿免疫
rhinorrhoea,鼻漏,耳鼻喉
ribosome,核糖体,细胞生物学
rupture,破裂,病理
sarcoma,肉瘤,肿瘤
sebum,皮脂,皮肤
secretion,分泌,生理
sedation,镇静,麻醉
seizure,癫痫发作,神经
senescence,衰老,细胞生物学
sepsis,脓毒症,感染
sequela,后遗症,临床
serotonin,5-羟色胺,神经
serum,血清,血液
shock,休克,急诊
skeletal,骨骼的,骨科
sodium,钠,生化
somatic,躯体的,生理
spasm,痉挛,症状
specimen,标本,检验
spermatozoon,精子,生殖
sphincter,括约肌,解剖
spindle,纺锤体,细胞生物学
spleen,脾脏,免疫
splenomegaly,脾大,血液
sputum,痰,呼吸
stenosis,狭窄,病理
stent,支架,心血管
steroid,类固醇,药理
stimulus,刺激,生理
stomach,胃,消化
stomatitis,口腔炎,消化
strain,菌株,微生物
stroke,卒中,神经
stroma,间质,组织学
subclinical,亚临床的,临床
subcutaneous,皮下的,临床
subluxation,半脱位,骨科
substrate,底物,生化
suction,吸引,手术
suppression,抑制,生理
surgery,外科,外科
susceptibility,易感性,免疫
suture,缝合,外科
synapse,突触,神经
syndrome,综合征,临床
synovium,滑膜,解剖
synthesis,合成,生化
systemic,全身性的,临床
systole,收缩期,心血管
tachycardia,心动过速,心血管
tendon,肌腱,解剖
teratogenic,致畸的,妇产科
termination,终止,临床
testosterone,睾酮,内分泌
tetanus,破伤风,感染
therapy,治疗,临床
thrombocyte,血小板,血液
thrombosis,血栓形成,心血管
thymus,胸腺,免疫
thyroid,甲状腺,内分泌
tissue,组织,基础医学
tolerability,耐受性,药理
tomography,断层扫描,影像
tonsil,扁桃体,免疫
topical,局部的,临床
toxicity,毒性,药理
toxin,毒素,微生物
trachea,气管,解剖
tract,道,解剖
transducer,换能器,设备
transfection,转染,分子生物学
transferrin,转铁蛋白,检验
transformation,转化,肿瘤
transfusion,输血,血液
translation,翻译,分子生物学
translocation,易位,遗传
transplantation,移植,移植
trauma,创伤,急诊
tremor,震颤,神经
triage,分诊,急诊
troponin,肌钙蛋白,检验
trunk,躯干,解剖
tubule,小管,解剖
tumor,肿瘤,肿瘤
turgor,充盈度,体检
ubiquitination,泛素化,生化
ulcer,溃疡,病理
ultrasound,超声,影像
umbilicus,脐,解剖
urea,尿素,生化
ureter,输尿管,泌尿
urethra,尿道,泌尿
urine,尿液,泌尿
uterus,子宫,妇产科
vaccination,疫苗接种,免疫
vagina,阴道,妇产科
valve,瓣膜,心血管
variant,变异体,遗传
vasculature,脉管系统,解剖
vasculitis,血管炎,风湿免疫
vasoconstriction,血管收缩,生理
vasodilation,血管舒张,生理
vector,载体,分子生物学
vein,静脉,解剖
ventilation,通气,呼吸
ventricle,心室,心血管
venule,微静脉,解剖
vessel,血管,解剖
viability,存活能力,细胞生物学
virulence,毒力,微生物
virus,病毒,微生物
visceral,内脏的,解剖
vitamin,维生素,营养
vomiting,呕吐,症状
vulnerability,易损性,临床
wheezing,喘息,呼吸
wound,伤口,外科
xenograft,异种移植物,移植
zygote,受精卵,生殖
""".strip()

def main():
    # 加载已有
    existing = {}
    if os.path.exists(VOCAB_FILE):
        with open(VOCAB_FILE, "r", encoding="utf-8-sig") as f:
            reader = csv.DictReader(f)
            for row in reader:
                en = (row.get("英文术语") or "").strip().lower()
                if en and en not in existing:
                    existing[en] = [
                        row.get("英文术语", "").strip(),
                        row.get("中文译名", "").strip(),
                        row.get("学科", "").strip(),
                    ]

    print(f"已有 {len(existing)} 条通用术语")

    new_count = 0
    for line in VOCAB.split("\n"):
        line = line.strip()
        if not line:
            continue
        parts = [p.strip() for p in line.split(",", 2)]
        if len(parts) >= 2:
            en_key = parts[0].lower()
            if en_key and en_key not in existing:
                subject = parts[2] if len(parts) >= 3 else "基础医学"
                existing[en_key] = [parts[0], parts[1], subject]
                new_count += 1

    print(f"新增 {new_count} 条")

    with open(VOCAB_FILE, "w", encoding="utf-8-sig", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["英文术语", "中文译名", "学科"])
        for row in existing.values():
            writer.writerow(row)

    print(f"→ 通用术语库总量: {len(existing)} 条")

if __name__ == "__main__":
    main()
